osx_image: xcode10.2
language: objective-c
script:
  - xcodebuild test -workspace Project-OC.xcworkspace -scheme Project-OC -destination "platform=iOS Simulator,name=iPhone Xr" | xcpretty -f `xcpretty-travis-formatter`