# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'Project-OC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Project-OC

  # pod 'Masonry'

  # pod 'IQKeyboardManager'

  pod 'SwpTextView/Object-C', :path => '../'

end
