project 'SwpTextViewDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '8.0'

target 'SwpTextViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwpTextViewDemo
  # inhibit_all_warnings!
  
  pod 'SwpTextView', :path => '../'
  pod 'IQKeyboardManager'
end
