# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'Project-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project-Swift
  inhibit_all_warnings!
  
  pod 'SnapKit'
  pod 'SwpTextView/Swift', :path => '../'

end
